name: snake101010
description: The game of snake

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # uic: ^0.4.2
  universal_platform: ^0.1.3
  # db
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1

  # detect swipes
  simple_gesture_detector: ^0.1.4
  # state management
  get_it: ^3.1.0
  provider: ^4.0.2

# dev_dependencies:
# flutter_test:
#   sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
    - family: VT323
      fonts:
        - asset: assets/fonts/VT323/VT323-Regular.ttf
